from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
import sqlite3
from datetime import date
from PyQt5.QtPrintSupport import *
from nsetting import Ui_File

class Ui_MainWindow(object):        

    def openWindow(self):
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_File()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1278, 839)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("*{\n"
"color:000;\n"
"border: none;\n"
"\n"
"}\n"
"\n"
"#centralwidget{\n"
"background-color:#eff9fa;\n"
"}\n"
"\n"
"#frame_5{\n"
"background-color:rgb(55,233,200);\n"
"}\n"
"QLineEdit{\n"
"background: transparent;\n"
"color: #062e70;\n"
"}\n"
"#searchFrame{\n"
"border-radius:10px;\n"
"border:2px solid #062e70;\n"
"}\n"
"#appHeader{\n"
"color:#062e70;\n"
"}\n"
"#card1,#card2,#card3,#card4{\n"
"background-color:#fefeff;\n"
"border-radius:20px;\n"
"}\n"
"#profileCont{\n"
"background-color:#fefeff;\n"
"border-radius:20px;\n"
"}\n"
"#headerFrame{\n"
"background-color:#fefeff;\n"
"}\n"
"#pushButton {\n"
"background-color:#fefeff;\n"
"padding:10px 5px;\n"
"text-align: left;\n"
"border-top-left-radius:20px;\n"
"\n"
"}\n"
"QPushButton{\n"
"\n"
"padding:10px 5px;\n"
"text-align: left;\n"
"}\n"
"#fame_9{\n"
"background-color:#fefeff;\n"
"border-radius:20px;\n"
"}\n"
"#mainFrame{background-color:#fefeff;\n"
"border-radius:20px;}\n"
"#leftMenu{\n"
"background-color:rgb(76,88,25);\n"
"}\n"
"#mainFrame{\n"
"    background-color: rgb(43, 92, 255);\n"
"}\n"
"#frame_10{\n"
"background-color:#fefeff;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton:hover{\n"
" background-color:#fefeff;\n"
" padding:10px 5px;\n"
" text-align: left;\n"
" border-top-left-radius:20px;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftMenu = QtWidgets.QWidget(self.centralwidget)
        self.leftMenu.setMinimumSize(QtCore.QSize(300, 0))
        self.leftMenu.setMaximumSize(QtCore.QSize(0, 16777215))
        self.leftMenu.setObjectName("leftMenu")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.leftMenu)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_5 = QtWidgets.QFrame(self.leftMenu)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_7.setContentsMargins(15, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.top = QtWidgets.QLabel(self.frame_6)
        self.top.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.top.setFont(font)
        self.top.setObjectName("top")
        self.horizontalLayout_13.addWidget(self.top, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_7.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(10)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        
        self.home_btn = QtWidgets.QPushButton(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.home_btn.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/blueIcon/iconsblue/home.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_btn.setIcon(icon)
        self.home_btn.setIconSize(QtCore.QSize(30, 30))
        self.home_btn.setObjectName("home_btn")
        self.verticalLayout_8.addWidget(self.home_btn)
        
        self.students_btn = QtWidgets.QPushButton(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.students_btn.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/blueIcon/iconsblue/users.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.students_btn.setIcon(icon1)
        self.students_btn.setIconSize(QtCore.QSize(30, 30))
        self.students_btn.setObjectName("students_btn")
        self.verticalLayout_8.addWidget(self.students_btn)

##################################################################################### Home
        self.edit_btn = QtWidgets.QPushButton(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.edit_btn.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/blueIcon/iconsblue/user-plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.edit_btn.setIcon(icon1)
        self.edit_btn.setIconSize(QtCore.QSize(30, 30))
        self.edit_btn.setObjectName("edit_btn")
        self.verticalLayout_8.addWidget(self.edit_btn)
#####################################################################################        
        self.fees_btn = QtWidgets.QPushButton(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.fees_btn.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/blueIcon/iconsblue/percent.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fees_btn.setIcon(icon2)
        self.fees_btn.setIconSize(QtCore.QSize(30, 30))
        self.fees_btn.setObjectName("fees_btn")
        self.verticalLayout_8.addWidget(self.fees_btn)
        self.report_btn = QtWidgets.QPushButton(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.report_btn.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/blueIcon/iconsblue/paperclip.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.report_btn.setIcon(icon3)
        self.report_btn.setIconSize(QtCore.QSize(30, 30))
        self.report_btn.setObjectName("report_btn")
        self.verticalLayout_8.addWidget(self.report_btn)
        #################################################
        self.setting_btn = QtWidgets.QPushButton(self.frame_8 ,clicked=lambda: self.openWindow())
        font = QtGui.QFont()
        font.setPointSize(11)
        self.setting_btn.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/blueIcon/iconsblue/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setting_btn.setIcon(icon4)
        self.setting_btn.setIconSize(QtCore.QSize(30, 30))
        self.setting_btn.setObjectName("setting_btn")
        self.verticalLayout_8.addWidget(self.setting_btn)
        self.verticalLayout_9.addWidget(self.frame_8, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_7.addWidget(self.frame_7)
        self.verticalLayout_6.addWidget(self.frame_5)
        self.horizontalLayout.addWidget(self.leftMenu)
        self.mainbody = QtWidgets.QWidget(self.centralwidget)
        self.mainbody.setMinimumSize(QtCore.QSize(40, 40))
        self.mainbody.setObjectName("mainbody")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainbody)
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerFrame = QtWidgets.QWidget(self.mainbody)
        self.headerFrame.setObjectName("headerFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.headerFrame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 10)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(self.headerFrame)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.menuBtn = QtWidgets.QPushButton(self.widget)
        self.menuBtn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/blueIcon/iconsblue/align-justify.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuBtn.setIcon(icon5)
        self.menuBtn.setIconSize(QtCore.QSize(32, 32))
        self.menuBtn.setObjectName("menuBtn")
        self.horizontalLayout_3.addWidget(self.menuBtn)
        self.appHeader = QtWidgets.QLabel(self.widget)
        self.appHeader.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.appHeader.setFont(font)
        self.appHeader.setObjectName("appHeader")
        self.horizontalLayout_3.addWidget(self.appHeader)
        self.horizontalLayout_2.addWidget(self.widget, 0, QtCore.Qt.AlignRight)
        self.widget_2 = QtWidgets.QWidget(self.headerFrame)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.searchFrame = QtWidgets.QFrame(self.widget_2)
        self.searchFrame.setMinimumSize(QtCore.QSize(360, 0))
        self.searchFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.searchFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.searchFrame.setObjectName("searchFrame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.searchFrame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.searchFrame)
        self.label_2.setMaximumSize(QtCore.QSize(47, 40))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/blueIcon/iconsblue/search.svg"))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.searchFrame)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_5.addWidget(self.lineEdit)
        self.horizontalLayout_4.addWidget(self.searchFrame, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.widget_2, 0, QtCore.Qt.AlignHCenter)
        self.widget_3 = QtWidgets.QWidget(self.headerFrame)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.accountBtn = QtWidgets.QPushButton(self.widget_3)
        self.accountBtn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/blueIcon/iconsblue/user.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.accountBtn.setIcon(icon6)
        self.accountBtn.setIconSize(QtCore.QSize(40, 40))
        self.accountBtn.setObjectName("accountBtn")
        self.horizontalLayout_6.addWidget(self.accountBtn)
        self.horizontalLayout_2.addWidget(self.widget_3, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.headerFrame, 0, QtCore.Qt.AlignTop)
        self.cardFrame = QtWidgets.QWidget(self.mainbody)
        self.cardFrame.setObjectName("cardFrame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.cardFrame)
        self.horizontalLayout_7.setContentsMargins(10, 10, 10, 0)
        self.horizontalLayout_7.setSpacing(20)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.card1 = QtWidgets.QFrame(self.cardFrame)
        self.card1.setMinimumSize(QtCore.QSize(160, 0))
        self.card1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.card1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.card1.setObjectName("card1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.card1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.card1)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setMaximumSize(QtCore.QSize(40, 40))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/blueIcon/iconsblue/bar-chart-2.svg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_8.addWidget(self.label_3)
        self.verticalLayout_2.addWidget(self.frame)
        self.label_4 = QtWidgets.QLabel(self.card1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout_7.addWidget(self.card1, 0, QtCore.Qt.AlignTop)
        self.card2 = QtWidgets.QFrame(self.cardFrame)
        self.card2.setMinimumSize(QtCore.QSize(160, 0))
        self.card2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.card2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.card2.setObjectName("card2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.card2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.card2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setMaximumSize(QtCore.QSize(40, 40))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/blueIcon/iconsblue/pen-tool.svg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.verticalLayout_3.addWidget(self.frame_2, 0, QtCore.Qt.AlignTop)
        self.label_7 = QtWidgets.QLabel(self.card2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_7.addWidget(self.card2, 0, QtCore.Qt.AlignTop)
        self.card4 = QtWidgets.QFrame(self.cardFrame)
        self.card4.setMinimumSize(QtCore.QSize(160, 0))
        self.card4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.card4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.card4.setObjectName("card4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.card4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_4 = QtWidgets.QFrame(self.card4)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_11 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.frame_4)
        self.label_12.setMaximumSize(QtCore.QSize(40, 40))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap(":/blueIcon/iconsblue/target.svg"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.verticalLayout_5.addWidget(self.frame_4, 0, QtCore.Qt.AlignTop)
        self.label_13 = QtWidgets.QLabel(self.card4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_5.addWidget(self.label_13, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_7.addWidget(self.card4, 0, QtCore.Qt.AlignTop)
        self.card3 = QtWidgets.QFrame(self.cardFrame)
        self.card3.setMinimumSize(QtCore.QSize(160, 0))
        self.card3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.card3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.card3.setObjectName("card3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.card3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_3 = QtWidgets.QFrame(self.card3)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        self.label_9.setMaximumSize(QtCore.QSize(40, 40))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/blueIcon/iconsblue/calendar.svg"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.verticalLayout_4.addWidget(self.frame_3, 0, QtCore.Qt.AlignTop)
        self.label_10 = QtWidgets.QLabel(self.card3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_7.addWidget(self.card3, 0, QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.cardFrame)
        self.mainFrame = QtWidgets.QWidget(self.mainbody)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainFrame.sizePolicy().hasHeightForWidth())
        self.mainFrame.setSizePolicy(sizePolicy)
        self.mainFrame.setObjectName("mainFrame")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.mainFrame)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.tabWidget = QtWidgets.QTabWidget(self.mainFrame)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setMaximumSize(QtCore.QSize(750, 600))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("background-color: rgb(41, 220, 181);")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.homepic = QtWidgets.QLabel(self.tab_5)
        self.homepic.setGeometry(QtCore.QRect(0, 0, 751, 501))
        self.homepic.setText("")
        self.homepic.setPixmap(QtGui.QPixmap("homepic.png"))
        self.homepic.setScaledContents(True)
        self.homepic.setObjectName("homepic")
        self.label_42 = QtWidgets.QLabel(self.tab_5)
        self.label_42.setGeometry(QtCore.QRect(20, 10, 711, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.tabWidget.addTab(self.tab_5, icon, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame_10 = QtWidgets.QFrame(self.tab)
        self.frame_10.setGeometry(QtCore.QRect(10, 10, 731, 80))
        self.frame_10.setStyleSheet("background-color:#fefeff;\n"
"border-radius:20px;")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_18 = QtWidgets.QLabel(self.frame_10)
        self.label_18.setGeometry(QtCore.QRect(200, 10, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(20, 130, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.tab)
        self.label_20.setGeometry(QtCore.QRect(20, 180, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.tab)
        self.label_21.setGeometry(QtCore.QRect(20, 230, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.tb11 = QtWidgets.QLineEdit(self.tab)
        self.tb11.setGeometry(QtCore.QRect(200, 130, 161, 31))
        self.tb11.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.tb11.setObjectName("tb11")
        self.tb12 = QtWidgets.QLineEdit(self.tab)
        self.tb12.setGeometry(QtCore.QRect(200, 180, 161, 31))
        self.tb12.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.tb12.setObjectName("tb12")
        self.cb11 = QtWidgets.QComboBox(self.tab)
        self.cb11.setGeometry(QtCore.QRect(200, 231, 161, 31))
        self.cb11.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.cb11.setObjectName("cb11")
        self.cb11.addItem("")
        self.cb11.addItem("")
        self.cb11.addItem("")
        self.label_26 = QtWidgets.QLabel(self.tab)
        self.label_26.setGeometry(QtCore.QRect(20, 280, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.tb13 = QtWidgets.QLineEdit(self.tab)
        self.tb13.setGeometry(QtCore.QRect(200, 280, 161, 31))
        self.tb13.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.tb13.setObjectName("tb13")
        self.label_27 = QtWidgets.QLabel(self.tab)
        self.label_27.setGeometry(QtCore.QRect(20, 330, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.tb14 = QtWidgets.QLineEdit(self.tab)
        self.tb14.setGeometry(QtCore.QRect(200, 330, 161, 31))
        self.tb14.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.tb14.setObjectName("tb14")
        self.label_28 = QtWidgets.QLabel(self.tab)
        self.label_28.setGeometry(QtCore.QRect(20, 400, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.mtb11 = QtWidgets.QTextEdit(self.tab)
        self.mtb11.setGeometry(QtCore.QRect(200, 380, 161, 87))
        self.mtb11.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"boarder-radius:20px;")
        self.mtb11.setObjectName("mtb11")
        self.label_29 = QtWidgets.QLabel(self.tab)
        self.label_29.setGeometry(QtCore.QRect(390, 130, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.tb15 = QtWidgets.QLineEdit(self.tab)
        self.tb15.setGeometry(QtCore.QRect(550, 130, 181, 31))
        self.tb15.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.tb15.setObjectName("tb15")
        self.label_30 = QtWidgets.QLabel(self.tab)
        self.label_30.setGeometry(QtCore.QRect(390, 180, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.tb16 = QtWidgets.QLineEdit(self.tab)
        self.tb16.setGeometry(QtCore.QRect(550, 180, 181, 31))
        self.tb16.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.tb16.setObjectName("tb16")
        self.cb12 = QtWidgets.QComboBox(self.tab)
        self.cb12.setGeometry(QtCore.QRect(550, 230, 181, 31))
        self.cb12.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.cb12.setObjectName("cb12")
        self.cb12.addItem("")
        self.cb12.addItem("")
        self.cb12.addItem("")
        self.label_31 = QtWidgets.QLabel(self.tab)
        self.label_31.setGeometry(QtCore.QRect(390, 229, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.cb13 = QtWidgets.QComboBox(self.tab)
        self.cb13.setGeometry(QtCore.QRect(550, 281, 181, 31))
        self.cb13.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.cb13.setObjectName("cb13")
        self.cb13.addItem("")
        self.cb13.addItem("")
        self.cb13.addItem("")
        self.cb13.addItem("")
        self.cb13.addItem("")
        self.cb13.addItem("")
        self.label_32 = QtWidgets.QLabel(self.tab)
        self.label_32.setGeometry(QtCore.QRect(390, 280, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.b12 = QtWidgets.QPushButton(self.tab)
        self.b12.setGeometry(QtCore.QRect(490, 400, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.b12.setFont(font)
        self.b12.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 85, 255);\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 50, 255);\n"
"    border:2px solid rgb(32, 47, 255);\n"
"}\n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/blueIcon/iconsblue/save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b12.setIcon(icon7)
        self.b12.setIconSize(QtCore.QSize(30, 30))
        self.b12.setObjectName("b12")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/blueIcon/iconsblue/upload.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon8, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame_11 = QtWidgets.QFrame(self.tab_2)
        self.frame_11.setGeometry(QtCore.QRect(10, 10, 731, 80))
        self.frame_11.setStyleSheet("background-color:#fefeff;\n"
"border-radius:20px;")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_22 = QtWidgets.QLabel(self.frame_11)
        self.label_22.setGeometry(QtCore.QRect(170, 10, 431, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_54 = QtWidgets.QLabel(self.tab_2)
        self.label_54.setGeometry(QtCore.QRect(20, 129, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.tab_2)
        self.label_55.setGeometry(QtCore.QRect(20, 179, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.tb21 = QtWidgets.QLineEdit(self.tab_2)
        self.tb21.setGeometry(QtCore.QRect(200, 179, 161, 31))
        self.tb21.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.tb21.setObjectName("tb21")
        self.label_70 = QtWidgets.QLabel(self.tab_2)
        self.label_70.setGeometry(QtCore.QRect(20, 229, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_70.setFont(font)
        self.label_70.setObjectName("label_70")
        self.tb23 = QtWidgets.QLineEdit(self.tab_2)
        self.tb23.setGeometry(QtCore.QRect(200, 279, 161, 31))
        self.tb23.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.tb23.setObjectName("tb23")
        self.label_71 = QtWidgets.QLabel(self.tab_2)
        self.label_71.setGeometry(QtCore.QRect(20, 279, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_71.setFont(font)
        self.label_71.setObjectName("label_71")
        self.tb24 = QtWidgets.QLineEdit(self.tab_2)
        self.tb24.setGeometry(QtCore.QRect(200, 329, 161, 31))
        self.tb24.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.tb24.setObjectName("tb24")
        self.label_72 = QtWidgets.QLabel(self.tab_2)
        self.label_72.setGeometry(QtCore.QRect(20, 329, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_72.setFont(font)
        self.label_72.setObjectName("label_72")
        self.label_73 = QtWidgets.QLabel(self.tab_2)
        self.label_73.setGeometry(QtCore.QRect(20, 400, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_73.setFont(font)
        self.label_73.setObjectName("label_73")
        self.mtb21 = QtWidgets.QTextEdit(self.tab_2)
        self.mtb21.setGeometry(QtCore.QRect(200, 380, 161, 87))
        self.mtb21.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"boarder-radius:20px;")
        self.mtb21.setObjectName("mtb21")
        self.label_74 = QtWidgets.QLabel(self.tab_2)
        self.label_74.setGeometry(QtCore.QRect(390, 179, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_74.setFont(font)
        self.label_74.setObjectName("label_74")
        self.label_75 = QtWidgets.QLabel(self.tab_2)
        self.label_75.setGeometry(QtCore.QRect(390, 279, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_75.setFont(font)
        self.label_75.setObjectName("label_75")
        self.label_76 = QtWidgets.QLabel(self.tab_2)
        self.label_76.setGeometry(QtCore.QRect(390, 129, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_76.setFont(font)
        self.label_76.setObjectName("label_76")
        self.tb26 = QtWidgets.QLineEdit(self.tab_2)
        self.tb26.setGeometry(QtCore.QRect(550, 179, 181, 31))
        self.tb26.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.tb26.setObjectName("tb26")
        self.label_77 = QtWidgets.QLabel(self.tab_2)
        self.label_77.setGeometry(QtCore.QRect(390, 228, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_77.setFont(font)
        self.label_77.setObjectName("label_77")
        self.tb25 = QtWidgets.QLineEdit(self.tab_2)
        self.tb25.setGeometry(QtCore.QRect(550, 129, 181, 31))
        self.tb25.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.tb25.setObjectName("tb25")
        self.b22 = QtWidgets.QPushButton(self.tab_2)
        self.b22.setGeometry(QtCore.QRect(550, 410, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.b22.setFont(font)
        self.b22.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 85, 255);\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 50, 255);\n"
"    border:2px solid rgb(32, 47, 255);\n"
"}\n"
"")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/blueIcon/iconsblue/delete.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b22.setIcon(icon9)
        self.b22.setIconSize(QtCore.QSize(30, 30))
        self.b22.setObjectName("b22")
        self.b21 = QtWidgets.QPushButton(self.tab_2)
        self.b21.setGeometry(QtCore.QRect(380, 410, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.b21.setFont(font)
        self.b21.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 85, 255);\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 50, 255);\n"
"    border:2px solid rgb(32, 47, 255);\n"
"}\n"
"")
        self.b21.setIcon(icon7)
        self.b21.setIconSize(QtCore.QSize(30, 30))
        self.b21.setObjectName("b21")
        self.cb21 = QtWidgets.QComboBox(self.tab_2)
        self.cb21.setGeometry(QtCore.QRect(200, 130, 161, 31))
        self.cb21.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.cb21.setObjectName("cb21")
        self.tb22 = QtWidgets.QLineEdit(self.tab_2)
        self.tb22.setGeometry(QtCore.QRect(200, 230, 161, 31))
        self.tb22.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.tb22.setObjectName("tb22")
        self.tb27 = QtWidgets.QLineEdit(self.tab_2)
        self.tb27.setGeometry(QtCore.QRect(550, 230, 181, 31))
        self.tb27.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.tb27.setObjectName("tb27")
        self.tb28 = QtWidgets.QLineEdit(self.tab_2)
        self.tb28.setGeometry(QtCore.QRect(550, 280, 181, 31))
        self.tb28.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.tb28.setObjectName("tb28")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/blueIcon/iconsblue/edit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon10, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 351, 481))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.frame_12 = QtWidgets.QFrame(self.groupBox)
        self.frame_12.setGeometry(QtCore.QRect(0, 30, 341, 71))
        self.frame_12.setStyleSheet("background-color:#fefeff;\n"
"border-radius:20px;")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label_23 = QtWidgets.QLabel(self.frame_12)
        self.label_23.setGeometry(QtCore.QRect(10, 10, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.groupBox)
        self.label_24.setGeometry(QtCore.QRect(0, 130, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.tb31 = QtWidgets.QLineEdit(self.groupBox)
        self.tb31.setGeometry(QtCore.QRect(180, 130, 161, 31))
        self.tb31.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.tb31.setObjectName("tb31")
        self.cb31 = QtWidgets.QComboBox(self.groupBox)
        self.cb31.setGeometry(QtCore.QRect(180, 180, 161, 31))
        self.cb31.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.cb31.setObjectName("cb31")
        self.label_25 = QtWidgets.QLabel(self.groupBox)
        self.label_25.setGeometry(QtCore.QRect(0, 180, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_33 = QtWidgets.QLabel(self.groupBox)
        self.label_33.setGeometry(QtCore.QRect(0, 230, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.tb32 = QtWidgets.QLineEdit(self.groupBox)
        self.tb32.setGeometry(QtCore.QRect(180, 230, 161, 31))
        self.tb32.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.tb32.setText("")
        self.tb32.setObjectName("tb32")
        self.label_34 = QtWidgets.QLabel(self.groupBox)
        self.label_34.setGeometry(QtCore.QRect(0, 280, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.tb33 = QtWidgets.QLineEdit(self.groupBox)
        self.tb33.setGeometry(QtCore.QRect(180, 280, 161, 31))
        self.tb33.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.tb33.setText("")
        self.tb33.setObjectName("tb33")
        self.label_35 = QtWidgets.QLabel(self.groupBox)
        self.label_35.setGeometry(QtCore.QRect(0, 330, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.tb34 = QtWidgets.QLineEdit(self.groupBox)
        self.tb34.setGeometry(QtCore.QRect(180, 330, 161, 31))
        self.tb34.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.tb34.setText("")
        self.tb34.setObjectName("tb34")
        self.b31 = QtWidgets.QPushButton(self.groupBox)
        self.b31.setGeometry(QtCore.QRect(50, 410, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.b31.setFont(font)
        self.b31.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 85, 255);\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 50, 255);\n"
"    border:2px solid rgb(32, 47, 255);\n"
"}\n"
"")
        self.b31.setIcon(icon7)
        self.b31.setIconSize(QtCore.QSize(30, 30))
        self.b31.setObjectName("b31")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_2.setGeometry(QtCore.QRect(380, 10, 351, 481))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.frame_14 = QtWidgets.QFrame(self.groupBox_2)
        self.frame_14.setGeometry(QtCore.QRect(0, 30, 351, 71))
        self.frame_14.setStyleSheet("background-color:#fefeff;\n"
"border-radius:20px;")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.label_43 = QtWidgets.QLabel(self.frame_14)
        self.label_43.setGeometry(QtCore.QRect(20, 10, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.groupBox_2)
        self.label_44.setGeometry(QtCore.QRect(0, 130, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.groupBox_2)
        self.label_45.setGeometry(QtCore.QRect(0, 180, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.groupBox_2)
        self.label_46.setGeometry(QtCore.QRect(0, 230, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.tb36 = QtWidgets.QLineEdit(self.groupBox_2)
        self.tb36.setGeometry(QtCore.QRect(180, 230, 161, 31))
        self.tb36.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.tb36.setText("")
        self.tb36.setObjectName("tb36")
        self.label_47 = QtWidgets.QLabel(self.groupBox_2)
        self.label_47.setGeometry(QtCore.QRect(0, 280, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.tb37 = QtWidgets.QLineEdit(self.groupBox_2)
        self.tb37.setGeometry(QtCore.QRect(180, 280, 161, 31))
        self.tb37.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.tb37.setText("")
        self.tb37.setObjectName("tb37")
        self.label_48 = QtWidgets.QLabel(self.groupBox_2)
        self.label_48.setGeometry(QtCore.QRect(0, 330, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.tb38 = QtWidgets.QLineEdit(self.groupBox_2)
        self.tb38.setGeometry(QtCore.QRect(180, 330, 161, 31))
        self.tb38.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.tb38.setText("")
        self.tb38.setObjectName("tb38")
        self.b32 = QtWidgets.QPushButton(self.groupBox_2)
        self.b32.setGeometry(QtCore.QRect(0, 410, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.b32.setFont(font)
        self.b32.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 85, 255);\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 50, 255);\n"
"    border:2px solid rgb(32, 47, 255);\n"
"}\n"
"")
        self.b32.setIcon(icon7)
        self.b32.setIconSize(QtCore.QSize(30, 30))
        self.b32.setObjectName("b32")
        self.cb32 = QtWidgets.QComboBox(self.groupBox_2)
        self.cb32.setGeometry(QtCore.QRect(180, 130, 161, 31))
        self.cb32.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.cb32.setObjectName("cb32")
        self.tb35 = QtWidgets.QLineEdit(self.groupBox_2)
        self.tb35.setGeometry(QtCore.QRect(180, 180, 161, 31))
        self.tb35.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.tb35.setText("")
        self.tb35.setObjectName("tb35")
        self.b33 = QtWidgets.QPushButton(self.groupBox_2)
        self.b33.setGeometry(QtCore.QRect(180, 410, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.b33.setFont(font)
        self.b33.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 85, 255);\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 50, 255);\n"
"    border:2px solid rgb(32, 47, 255);\n"
"}\n"
"")
        self.b33.setIcon(icon9)
        self.b33.setIconSize(QtCore.QSize(30, 30))
        self.b33.setObjectName("b33")
        self.tabWidget.addTab(self.tab_3, icon2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tableReport = QtWidgets.QTableWidget(self.tab_4)
        self.tableReport.setGeometry(QtCore.QRect(10, 160, 731, 321))
        self.tableReport.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.tableReport.setObjectName("tableReport")
        self.tableReport.setColumnCount(0)
        self.tableReport.setRowCount(0)
        self.frame_15 = QtWidgets.QFrame(self.tab_4)
        self.frame_15.setGeometry(QtCore.QRect(10, 10, 731, 80))
        self.frame_15.setStyleSheet("background-color:#fefeff;\n"
"border-radius:20px;")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.label_49 = QtWidgets.QLabel(self.frame_15)
        self.label_49.setGeometry(QtCore.QRect(130, 10, 451, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.l61 = QtWidgets.QLabel(self.tab_4)
        self.l61.setGeometry(QtCore.QRect(210, 107, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.l61.setFont(font)
        self.l61.setAlignment(QtCore.Qt.AlignCenter)
        self.l61.setObjectName("l61")
        self.tabWidget.addTab(self.tab_4, icon3, "")

        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.label_50 = QtWidgets.QLabel(self.tab_6)
        self.label_50.setGeometry(QtCore.QRect(20, 10, 711, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_50.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.tab_6)
        self.label_51.setGeometry(QtCore.QRect(220, 120, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_51.setFont(font)
        self.label_51.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_51.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.tab_6)
        self.label_52.setGeometry(QtCore.QRect(50, 70, 651, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_52.setFont(font)
        self.label_52.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_52.setStyleSheet("")
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.tab_6)
        self.label_53.setGeometry(QtCore.QRect(0, 260, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_53.setFont(font)
        self.label_53.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_53.setStyleSheet("")
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setObjectName("label_53")
        self.label_56 = QtWidgets.QLabel(self.tab_6)
        self.label_56.setGeometry(QtCore.QRect(330, 260, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_56.setStyleSheet("")
        self.label_56.setAlignment(QtCore.Qt.AlignCenter)
        self.label_56.setObjectName("label_56")
        self.l83 = QtWidgets.QLabel(self.tab_6)
        self.l83.setGeometry(QtCore.QRect(140, 260, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.l83.setFont(font)
        self.l83.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.l83.setStyleSheet("")
        self.l83.setAlignment(QtCore.Qt.AlignCenter)
        self.l83.setObjectName("l83")
        self.label_58 = QtWidgets.QLabel(self.tab_6)
        self.label_58.setGeometry(QtCore.QRect(480, 190, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_58.setFont(font)
        self.label_58.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_58.setStyleSheet("")
        self.label_58.setAlignment(QtCore.Qt.AlignCenter)
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.tab_6)
        self.label_59.setGeometry(QtCore.QRect(480, 220, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_59.setFont(font)
        self.label_59.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_59.setStyleSheet("")
        self.label_59.setAlignment(QtCore.Qt.AlignCenter)
        self.label_59.setObjectName("label_59")
        self.l84 = QtWidgets.QLabel(self.tab_6)
        self.l84.setGeometry(QtCore.QRect(580, 260, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.l84.setFont(font)
        self.l84.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.l84.setStyleSheet("")
        self.l84.setAlignment(QtCore.Qt.AlignCenter)
        self.l84.setObjectName("l84")
        self.label_61 = QtWidgets.QLabel(self.tab_6)
        self.label_61.setGeometry(QtCore.QRect(10, 310, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_61.setFont(font)
        self.label_61.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_61.setStyleSheet("")
        self.label_61.setAlignment(QtCore.Qt.AlignCenter)
        self.label_61.setObjectName("label_61")
        self.l85 = QtWidgets.QLabel(self.tab_6)
        self.l85.setGeometry(QtCore.QRect(60, 310, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.l85.setFont(font)
        self.l85.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.l85.setStyleSheet("")
        self.l85.setAlignment(QtCore.Qt.AlignCenter)
        self.l85.setObjectName("l85")
        self.label_63 = QtWidgets.QLabel(self.tab_6)
        self.label_63.setGeometry(QtCore.QRect(330, 310, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_63.setFont(font)
        self.label_63.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_63.setStyleSheet("")
        self.label_63.setAlignment(QtCore.Qt.AlignCenter)
        self.label_63.setObjectName("label_63")
        self.l86 = QtWidgets.QLabel(self.tab_6)
        self.l86.setGeometry(QtCore.QRect(370, 310, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.l86.setFont(font)
        self.l86.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.l86.setStyleSheet("")
        self.l86.setAlignment(QtCore.Qt.AlignCenter)
        self.l86.setObjectName("l86")
        self.label_65 = QtWidgets.QLabel(self.tab_6)
        self.label_65.setGeometry(QtCore.QRect(230, 360, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_65.setFont(font)
        self.label_65.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_65.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_65.setAlignment(QtCore.Qt.AlignCenter)
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(self.tab_6)
        self.label_66.setGeometry(QtCore.QRect(560, 470, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_66.setFont(font)
        self.label_66.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_66.setStyleSheet("")
        self.label_66.setAlignment(QtCore.Qt.AlignCenter)
        self.label_66.setObjectName("label_66")
        self.b81 = QtWidgets.QPushButton(self.tab_6)
        self.b81.setGeometry(QtCore.QRect(20, 440, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.b81.setFont(font)
        self.b81.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 85, 255);\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 50, 255);\n"
"    border:2px solid rgb(32, 47, 255);\n"
"}\n"
"")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/blueIcon/iconsblue/printer.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b81.setIcon(icon11)
        self.b81.setIconSize(QtCore.QSize(30, 30))
        self.b81.setObjectName("b81")
        self.b82 = QtWidgets.QPushButton(self.tab_6)
        self.b82.setGeometry(QtCore.QRect(200, 440, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.b82.setFont(font)
        self.b82.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 85, 255);\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 50, 255);\n"
"    border:2px solid rgb(32, 47, 255);\n"
"}\n"
"")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/blueIcon/iconsblue/crop.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b82.setIcon(icon12)
        self.b82.setIconSize(QtCore.QSize(30, 30))
        self.b82.setObjectName("b82")
        self.l81 = QtWidgets.QLabel(self.tab_6)
        self.l81.setGeometry(QtCore.QRect(620, 190, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.l81.setFont(font)
        self.l81.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.l81.setStyleSheet("")
        self.l81.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.l81.setObjectName("l81")
        self.l82 = QtWidgets.QLabel(self.tab_6)
        self.l82.setGeometry(QtCore.QRect(560, 220, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.l82.setFont(font)
        self.l82.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.l82.setStyleSheet("")
        self.l82.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.l82.setObjectName("l82")
        self.tabWidget.addTab(self.tab_6, icon11, "")
        ###########################################################################
        ###########################################################################
        self.horizontalLayout_12.addWidget(self.tabWidget)
        self.verticalLayout.addWidget(self.mainFrame)
        self.horizontalLayout.addWidget(self.mainbody)
        self.profileCont = QtWidgets.QWidget(self.centralwidget)
        self.profileCont.setObjectName("profileCont")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.profileCont)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_9 = QtWidgets.QFrame(self.profileCont)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_17 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_11.addWidget(self.label_17, 0, QtCore.Qt.AlignTop)
        self.label_16 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_11.addWidget(self.label_16, 0, QtCore.Qt.AlignTop)
        self.label_15 = QtWidgets.QLabel(self.frame_9)
        self.label_15.setMinimumSize(QtCore.QSize(80, 80))
        self.label_15.setMaximumSize(QtCore.QSize(80, 80))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("jims_logo.webp"))
        self.label_15.setScaledContents(True)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_11.addWidget(self.label_15, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.myprofile_btn = QtWidgets.QPushButton(self.frame_9)
        self.myprofile_btn.setIcon(icon6)
        self.myprofile_btn.setIconSize(QtCore.QSize(30, 30))
        self.myprofile_btn.setObjectName("myprofile_btn")
        self.verticalLayout_11.addWidget(self.myprofile_btn)
        self.logout_btn = QtWidgets.QPushButton(self.frame_9)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/blueIcon/iconsblue/log-out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logout_btn.setIcon(icon13)
        self.logout_btn.setIconSize(QtCore.QSize(30, 30))
        self.logout_btn.setObjectName("logout_btn")
        self.verticalLayout_11.addWidget(self.logout_btn)
        self.verticalLayout_10.addWidget(self.frame_9, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout.addWidget(self.profileCont)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

####################################### All Changes ####################################
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget.tabBar().setVisible(False)

        self.home_btn.clicked.connect(self.show_home_tab)

        self.students_btn.clicked.connect(self.show_add_new_student_tab)
        self.b12.clicked.connect(self.save_student_details)
        
        self.edit_btn.clicked.connect(self.show_edit_student_tab)
        #self.show_edit_student_tab()
        self.cb21.currentIndexChanged.connect(self.fill_details_when_combobox_selected)
        self.b21.clicked.connect(self.edit_student_details)
        self.b22.clicked.connect(self.delete_student_details)

        self.fees_btn.clicked.connect(self.show_fees_tab)
        self.b31.clicked.connect(self.save_fees_details)

        self.cb32.currentIndexChanged.connect(self.fill_receipt_details_in_textbox_for_edit_fees_tab)
        self.b32.clicked.connect(self.update_fees_details)
        self.b33.clicked.connect(self.delete_fees_details)

        self.report_btn.clicked.connect(self.show_report_tab)

        self.logout_btn.clicked.connect(self.logout)
        self.logout_btn.clicked.connect(MainWindow.close)

###################################### Print_file ###############################################
        #self.b81.clicked.connect(self.print_file) #error
        self.b82.clicked.connect(self.cancel_print)

#####################################################################################
####################################### QMessage-1 ####################################    
    def showMessageBox(self,title,message):
        msgBox=QtWidgets.QMessageBox()
        msgBox.setIcon(QtWidgets.QMessageBox.Information)
        msgBox.setWindowTitle(title)
        msgBox.setText(message)
        msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msgBox.exec_()
    
####################################### Search ####################################
#     def search(self):
#         try:
#             connection=sqlite3.connect("College_Details.db")
#             cursor=connection.cursor()
#             cursor.execute("Select * from Student_info where name like '%"+self.lineEdit.text()+"%'")
#             row=cursor.fetchall()

#         except sqlite3.Error as e:
#             print("Error occured in search!"+e)

        
####################################### Add All Tabs ####################################    
    def show_home_tab(self):
        self.tabWidget.setCurrentIndex(0)

    def show_add_new_student_tab(self):
        self.tabWidget.setCurrentIndex(1)
        self.fill_next_registration_number()

    def show_fees_tab(self):
        self.tabWidget.setCurrentIndex(3)
        self.fill_registration_number_in_fees_tab()
        self.fill_next_receipt_number()
        self.tb34.setText(str(date.today()))
        self.fill_receipt_number_in_edit_fees_tab()

####################################### Reports ####################################
    def show_report_tab(self):
        self.tabWidget.setCurrentIndex(4)
        self.l61.setText("Student Reports")
        try:
            self.tableReport.setRowCount(0)
            connection=sqlite3.connect("College_Details.db")
            cursor=connection.cursor()
            cursor.execute("Select registration_number,full_name,gender,date_of_birth,address,phone,email,course,semester,age from Student_info")
            result=cursor.fetchall()
            r=0
            c=0
            for row_number,row_data in enumerate(result):
                r+=1
                c=0
                for row_number,data in enumerate(row_data):
                    c+=1
                self.tableReport.clear()
                self.tableReport.setColumnCount(c)
                for row_number,row_data in enumerate(result):
                    self.tableReport.insertRow(row_number)
                    for column_number, data in enumerate(row_data):
                        self.tableReport.setItem(row_number, column_number,QTableWidgetItem(str(data)))
                self.tableReport.setHorizontalHeaderLabels(['Registeration Number','Name','Gender','Date of birth','Address','Phone_No','Email','Course','Semester','Age'])
        except sqlite3.Error as e:
            print("Error occured in show student report!"+e)

####################################### Fill auto reg_no ####################################
    def fill_next_registration_number(self):    
        try:
                rn=0
                connection=sqlite3.connect("College_Details.db")
                cursor=connection.cursor()
                cursor.execute("Select * from Student_info")
                result=cursor.fetchall()
                if result:
                        for stud in result:
                                rn=(rn+1)
                self.tb11.setText(str(rn+1))
        except sqlite3.Error as e:
                print("Error occured in select student reg number!"+e)
        
####################################### Add student ####################################
    def save_student_details(self):
        try:
                connection=sqlite3.connect("College_Details.db")
                cursor=connection.cursor()

                registration_number=self.tb11.text()
                full_name=self.tb12.text()
                gender=self.cb11.currentText()
                date_of_birth=self.tb13.text()
                age=self.tb14.text()
                address=self.mtb11.toPlainText()
                phone=self.tb15.text()
                email=self.tb16.text()
                course=self.cb12.currentText()
                semester=self.cb13.currentText()

                #qry="Insert into Student_info (registration_number,full_name,gender,date_of_birth,age ,address,phone,email,course,semester) values(?,?,?,?,?,?,?,?,?,?);"
                #value=(registration_number,full_name,gender,date_of_birth,age,address,phone,email,course,semester)
                #connection.execute(qry,(value))
                cursor.execute("Insert into Student_info (registration_number,full_name,gender,date_of_birth,age ,address,phone,email,course,semester) VALUES(?,?,?,?,?,?,?,?,?,?)",(registration_number,full_name,gender,date_of_birth,age,address,phone,email,course,semester,))
                connection.commit()
                print("Student Details Added Successfully!")
                self.showMessageBox('College Management System','Student Details Added Successfully!')
        
        except sqlite3.Error as e:
                print("Error occured in save student details!"+e)
                

#120,shiv Street,Uttarakhand-22 %s,%s,%s,%s,%s,%s,%s,%s,%s,%s
####################################### Edit student #################################### 
    def show_edit_student_tab(self):
        self.tabWidget.setCurrentIndex(2)
        self.fill_registration_number_in_combobox()

    def fill_registration_number_in_combobox(self):    
        try:
                self.cb21.clear()
                connection=sqlite3.connect("College_Details.db")
                cursor=connection.cursor()
                cursor.execute("Select * from Student_info")
                result=cursor.fetchall()
                if result:
                    for stud in result:
                        self.cb21.addItem(str(stud[1]))
        except sqlite3.Error as e:
                print("Error occured in fill reg number in combobox!"+e)        
        
        
    def fill_details_when_combobox_selected(self):    
        try:
                details=self.cb21.currentText()
                connection=sqlite3.connect("College_Details.db")
                cursor=connection.cursor()
                cursor.execute("Select * from Student_info where registration_number= ? ;",(details,))
                result=cursor.fetchall()
                if result:
                    for stud in result:
                        self.tb21.setText(str(stud[2]))
                        self.tb22.setText(str(stud[3]))
                        self.tb23.setText(str(stud[4]))
                        self.tb24.setText(str(stud[10]))
                        self.mtb21.setText(str(stud[5]))
                        self.tb25.setText(str(stud[6]))
                        self.tb26.setText(str(stud[7]))
                        self.tb27.setText(str(stud[8]))
                        self.tb28.setText(str(stud[9]))
                        
        except sqlite3.Error as e:
                print("Error occured in fill details in combobox!"+e)                

    def edit_student_details(self):
        try:
                connection=sqlite3.connect("College_Details.db")
                cursor=connection.cursor()

                registration_number=self.cb21.currentText()
                full_name=self.tb21.text()
                gender=self.tb22.text()
                date_of_birth=self.tb23.text()
                age=self.tb24.text()
                address=self.mtb21.toPlainText()
                phone=self.tb25.text()
                email=self.tb26.text()
                course=self.tb27.text()
                semester=self.tb28.text()

                cursor.execute("Update Student_info set full_name='"+full_name+"',gender='"+gender+"',date_of_birth='"+date_of_birth+"',age='"+age+"',address='"+address+"',phone='"+phone+"',email='"+email+"',course='"+course+"',semester='"+semester+"' where registration_number= '"+registration_number+"'")
                connection.commit()
                print("Student Details Updated Successfully!")
                self.showMessageBox('College Management System','Student Details Updated Successfully!')
        
        except sqlite3.Error as e:
                print("Error occured in edit student details!"+e)

####################################### Delete student ####################################
    def delete_student_details(self):
        msg=QMessageBox()
        msg.setWindowTitle("Delete!!!")
        msg.setText("Are you sure you want to delete this student's details!")
        msg.setIcon(QMessageBox.Question)
        msg.setStandardButtons(QMessageBox.Yes|QMessageBox.No)
        msg.setDefaultButton(QMessageBox.No)
        x=msg.exec_()
        if x==QtWidgets.QMessageBox.Yes:
                try:
                    connection=sqlite3.connect("College_Details.db")
                    cursor=connection.cursor()

                    registration_number=self.cb21.currentText()

                    cursor.execute("Delete from Student_info where registration_number= '"+registration_number+"'")
                    connection.commit()
                    print("Student Details Deleted Successfully!")
                    self.showMessageBox('College Management System','Student Details Deleted Successfully!')
                    self.tabWidget.setCurrentIndex(0)
                except sqlite3.Error as e:
                    print("Error occured in delete student details!"+e)
        elif x==QtWidgets.QMessageBox.No:
                print("You Clicked No Button!")
        
        else:
                print("Sorry,You came to else condition!")

####################################### Fees ####################################
    def fill_registration_number_in_fees_tab(self):    
        try:
                self.cb31.clear()
                connection=sqlite3.connect("College_Details.db")
                cursor=connection.cursor()
                cursor.execute("Select * from Student_info")
                result=cursor.fetchall()
                if result:
                    for stud in result:
                        self.cb31.addItem(str(stud[1]))
        except sqlite3.Error as e:
                print("Error occured in fill reg number in fees_combobox!"+e)        

    def fill_next_receipt_number(self):    
        try:
                rn=0
                connection=sqlite3.connect("College_Details.db")
                cursor=connection.cursor()
                cursor.execute("Select * from fees")
                result=cursor.fetchall()
                if result:
                    for rec in result:
                        rn+=1
                self.tb31.setText(str(rn+1))
        except sqlite3.Error as e:
                print("Error occured in fill receipt number in fees!"+e)   

    def save_fees_details(self):
        try:
                connection=sqlite3.connect("College_Details.db")
                cursor=connection.cursor()

                receipt_no=self.tb31.text()
                registration_number=self.cb31.currentText()
                reason=self.tb32.text()
                amount=self.tb33.text()
                fees_date=self.tb34.text()

                cursor.execute("Insert into fees (receipt_number,registration_number,reason,amount,fees_date) VALUES(?,?,?,?,?)",(receipt_no,registration_number,reason,amount,fees_date,))
                connection.commit()
                print("Fees Details Added Successfully!")
                self.showMessageBox('College Management System','Fees Details Added Successfully!')
                self.fill_receipt_number_in_edit_fees_tab()
                self.l81.setText(self.tb31.text())
                self.l82.setText(self.tb34.text())
                self.l86.setText(self.tb34.text()) #date
                self.l84.setText(self.tb33.text()) #amount
                self.l85.setText(self.tb32.text()) #reason

                cursor.execute("Select * from Student_info where registration_number='"+registration_number+"'")
                result=cursor.fetchone()
                if result:
                        self.l83.setText(str(result[2]))
                self.tabWidget.setCurrentIndex(5)

                self.tb32.setText("")
                self.tb33.setText("")
                self.fill_next_receipt_number()
        except sqlite3.Error as e:
                print("Error occured in save fees details!"+e)  

####################################### Edit fees ####################################
    def fill_receipt_number_in_edit_fees_tab(self):    
        try:
                self.cb32.clear()
                connection=sqlite3.connect("College_Details.db")
                cursor=connection.cursor()
                cursor.execute("Select * from fees")
                result=cursor.fetchall()
                if result:
                    for rec in result:
                        self.cb32.addItem(str(rec[1]))
        except sqlite3.Error as e:
                print("Error occured in fill receipt number in fees_combobox!"+e)              

    def fill_receipt_details_in_textbox_for_edit_fees_tab(self):    
        try:
                connection=sqlite3.connect("College_Details.db")
                cursor=connection.cursor()
                cursor.execute("Select * from fees where receipt_number='"+self.cb32.currentText()+"'")
                result=cursor.fetchall()
                if result:
                    for rec in result:
                        self.tb35.setText(str(rec[2]))
                        self.tb36.setText(str(rec[3]))
                        self.tb37.setText(str(rec[4]))
                        self.tb38.setText(str(rec[5]))
        except sqlite3.Error as e:
                print("Error occured in fill receipt details in edit_fees_textbox!"+e)

    def update_fees_details(self):
        try:
                connection=sqlite3.connect("College_Details.db")
                cursor=connection.cursor()

                receipt_no=self.cb32.currentText()
                registration_number=self.tb35.text()
                reason=self.tb36.text()
                amount=self.tb37.text()
                fees_date=self.tb38.text()

                cursor.execute("Update fees set registration_number='"+registration_number+"',reason='"+reason+"',amount='"+amount+"',fees_date='"+fees_date+"' where receipt_number= '"+receipt_no+"'")
                connection.commit()
                print("Fees Details Updated Successfully!")
                self.showMessageBox('College Management System','Fees Details Updated Successfully!')
        
                self.l81.setText(self.cb32.currentText())
                self.l82.setText(self.tb38.text())
                self.l86.setText(self.tb38.text()) 
                self.l84.setText(self.tb37.text()) 
                self.l85.setText(self.tb36.text()) 

                cursor.execute("Select * from Student_info where registration_number='"+registration_number+"'")
                result=cursor.fetchone()
                if result:
                        self.l83.setText(str(result[2]))
                self.tabWidget.setCurrentIndex(5)
                self.tb35.setText("")
                self.tb36.setText("")
                self.tb37.setText("")
                self.tb38.setText("")
        except sqlite3.Error as e:
                print("Error occured in update fees details!"+e)


    def delete_fees_details(self):
        try:
                connection=sqlite3.connect("College_Details.db")
                cursor=connection.cursor()

                receipt_no=self.cb32.currentText()

                cursor.execute("Delete from fees where receipt_number= '"+receipt_no+"'")
                connection.commit()
                print("Fees Details Deleted Successfully!")
                self.showMessageBox('College Management System','Fees Details Deleted Successfully!')
        
                self.tb35.setText("")
                self.tb36.setText("")
                self.tb37.setText("")
                self.tb38.setText("")
                self.tabWidget.setCurrentIndex(0)
        except sqlite3.Error as e:
                print("Error occured in delete fees details!"+e)

####################################### Print ####################################
    def print_file(self):
        printer=QPrinter(QPrinter.HighResolution)
        dialog=QPrintDialog(printer,self)
        if dialog.exec_()==QPrintDialog.Accepted:
                self.tabWidget.print_(printer)

    def cancel_print(self):
        self.tabWidget.setCurrentIndex(0)

    def logout(self):
        print("Window Closed Successfully!")
        self.showMessageBox('College Management System','You have Logged Out Successfully!')

#####
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.top.setText(_translate("MainWindow", "Learn Clean"))
        self.home_btn.setText(_translate("MainWindow", "Home"))
        self.students_btn.setText(_translate("MainWindow", "Students"))
        self.edit_btn.setText(_translate("MainWindow", "Edit Details"))
        self.fees_btn.setText(_translate("MainWindow", "Fees"))
        self.report_btn.setText(_translate("MainWindow", "Report"))
        self.setting_btn.setText(_translate("MainWindow", "Settings"))
        self.appHeader.setText(_translate("MainWindow", "Dashboard"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Search"))
        self.label.setText(_translate("MainWindow", "5"))
        self.label_4.setText(_translate("MainWindow", "Attendance"))
        self.label_5.setText(_translate("MainWindow", "+5"))
        self.label_7.setText(_translate("MainWindow", "Lecture"))
        self.label_11.setText(_translate("MainWindow", "58"))
        self.label_13.setText(_translate("MainWindow", "coins"))
        self.label_8.setText(_translate("MainWindow", "2023"))
        self.label_10.setText(_translate("MainWindow", "year"))
        self.label_42.setText(_translate("MainWindow", "Welcome to College Home Menu"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Home"))
        self.label_18.setText(_translate("MainWindow", "Add New Student"))
        self.label_19.setText(_translate("MainWindow", "Registration Number"))
        self.label_20.setText(_translate("MainWindow", "Full Name"))
        self.label_21.setText(_translate("MainWindow", "Gender"))
        self.cb11.setItemText(0, _translate("MainWindow", "Male"))
        self.cb11.setItemText(1, _translate("MainWindow", "Female"))
        self.cb11.setItemText(2, _translate("MainWindow", "Other"))
        self.label_26.setText(_translate("MainWindow", "D.O.B"))
        self.label_27.setText(_translate("MainWindow", "Age"))
        self.label_28.setText(_translate("MainWindow", "Address"))
        self.label_29.setText(_translate("MainWindow", "Phone.No"))
        self.label_30.setText(_translate("MainWindow", "Email"))
        self.cb12.setItemText(0, _translate("MainWindow", "BCA"))
        self.cb12.setItemText(1, _translate("MainWindow", "BBA"))
        self.cb12.setItemText(2, _translate("MainWindow", "BJMC"))
        self.label_31.setText(_translate("MainWindow", "Course"))
        self.cb13.setItemText(0, _translate("MainWindow", "1st semester"))
        self.cb13.setItemText(1, _translate("MainWindow", "2nd semester"))
        self.cb13.setItemText(2, _translate("MainWindow", "3rd semester"))
        self.cb13.setItemText(3, _translate("MainWindow", "4th semester"))
        self.cb13.setItemText(4, _translate("MainWindow", "5th semester"))
        self.cb13.setItemText(5, _translate("MainWindow", "6th semester"))
        self.label_32.setText(_translate("MainWindow", "Semester"))
        self.b12.setText(_translate("MainWindow", "Save Details"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Add Student"))
        self.label_22.setText(_translate("MainWindow", "Edit Student Details "))
        self.label_54.setText(_translate("MainWindow", "Registration Number"))
        self.label_55.setText(_translate("MainWindow", "Full Name"))
        self.label_70.setText(_translate("MainWindow", "Gender"))
        self.label_71.setText(_translate("MainWindow", "D.O.B"))
        self.label_72.setText(_translate("MainWindow", "Age"))
        self.label_73.setText(_translate("MainWindow", "Address"))
        self.label_74.setText(_translate("MainWindow", "Email"))
        self.label_75.setText(_translate("MainWindow", "Semester"))
        self.label_76.setText(_translate("MainWindow", "Phone.No"))
        self.label_77.setText(_translate("MainWindow", "Course"))
        self.b22.setText(_translate("MainWindow", "Delete Details"))
        self.b21.setText(_translate("MainWindow", "Edit Details"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Edit Details"))
        self.groupBox.setTitle(_translate("MainWindow", "Add Fees Details"))
        self.label_23.setText(_translate("MainWindow", "Add Fees Details"))
        self.label_24.setText(_translate("MainWindow", "Receipt Number"))
        self.label_25.setText(_translate("MainWindow", "Registration Number"))
        self.label_33.setText(_translate("MainWindow", "Fees Pay Reason"))
        self.label_34.setText(_translate("MainWindow", "Amount"))
        self.label_35.setText(_translate("MainWindow", "Date"))
        self.b31.setText(_translate("MainWindow", "Save Fees Details"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Edit Fees Details"))
        self.label_43.setText(_translate("MainWindow", "Edit Fees Details"))
        self.label_44.setText(_translate("MainWindow", "Receipt Number"))
        self.label_45.setText(_translate("MainWindow", "Registration Number"))
        self.label_46.setText(_translate("MainWindow", "Fees Pay Reason"))
        self.label_47.setText(_translate("MainWindow", "Amount"))
        self.label_48.setText(_translate("MainWindow", "Date"))
        self.b32.setText(_translate("MainWindow", "Edit Details"))
        self.b33.setText(_translate("MainWindow", "Delete Details"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Fees Details"))
        self.label_49.setText(_translate("MainWindow", "Adminstrator Reports"))
        self.l61.setText(_translate("MainWindow", "Table Name"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Reports"))
        self.label_50.setText(_translate("MainWindow", "ABC International College !"))
        self.label_51.setText(_translate("MainWindow", "Fees Receipt"))
        self.label_52.setText(_translate("MainWindow", "xxxx Road, Street, City, State, (xxxx25), Phone: +1111 2222 5555"))
        self.label_53.setText(_translate("MainWindow", "Received from:"))
        self.label_56.setText(_translate("MainWindow", "the sum of amount Rupees:"))
        self.l83.setText(_translate("MainWindow", "-------------------------------"))
        self.label_58.setText(_translate("MainWindow", "Bill Number:"))
        self.label_59.setText(_translate("MainWindow", "Date :"))
        self.l84.setText(_translate("MainWindow", "-------------------------------"))
        self.label_61.setText(_translate("MainWindow", "For:"))
        self.l85.setText(_translate("MainWindow", "-------------------------------------------------------"))
        self.label_63.setText(_translate("MainWindow", "on"))
        self.l86.setText(_translate("MainWindow", "-----------------------------------------------"))
        self.label_65.setText(_translate("MainWindow", "Thank You"))
        self.label_66.setText(_translate("MainWindow", "Date and Signature"))
        self.b81.setText(_translate("MainWindow", "Print Receipt"))
        self.b82.setText(_translate("MainWindow", "Cancle"))
        self.l81.setText(_translate("MainWindow", "bill"))
        self.l82.setText(_translate("MainWindow", "bill"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Print Receipt"))
        self.label_17.setText(_translate("MainWindow", "Profile"))
        self.label_16.setText(_translate("MainWindow", "Admin"))
        self.myprofile_btn.setText(_translate("MainWindow", "My Profile"))
        self.logout_btn.setText(_translate("MainWindow", "Log Out"))

import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

